global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:5656']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80'] 